// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240306214050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9048),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9115),
                            EnclosureId = 4,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9128),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9131),
                            EnclosureId = 2,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 3,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9138),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9141),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 4,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9151),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9154),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 5,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9160),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9163),
                            EnclosureId = 3,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9170),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9173),
                            EnclosureId = 4,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9179),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9182),
                            EnclosureId = 3,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 8,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9191),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9193),
                            EnclosureId = 3,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 9,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9200),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9203),
                            EnclosureId = 1,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 10,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9210),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9213),
                            EnclosureId = 2,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 11,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9304),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9307),
                            EnclosureId = 1,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 12,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9317),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9319),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 13,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9326),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9329),
                            EnclosureId = 2,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 14,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9335),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9338),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 15,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9344),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9347),
                            EnclosureId = 3,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 16,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9356),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9358),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 17,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9365),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9368),
                            EnclosureId = 2,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 18,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9374),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9377),
                            EnclosureId = 1,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 19,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9384),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9387),
                            EnclosureId = 2,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 20,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9395),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9398),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 21,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9404),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9407),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 22,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9413),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9416),
                            EnclosureId = 2,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 23,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9423),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9426),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 24,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9434),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9437),
                            EnclosureId = 4,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 25,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9443),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9446),
                            EnclosureId = 1,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 26,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9452),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9455),
                            EnclosureId = 2,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 27,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9462),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9464),
                            EnclosureId = 3,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 28,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9473),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9476),
                            EnclosureId = 1,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 29,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9482),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9485),
                            EnclosureId = 1,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 30,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9491),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9494),
                            EnclosureId = 3,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 31,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9501),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9503),
                            EnclosureId = 4,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 32,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9512),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9515),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 33,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9521),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9524),
                            EnclosureId = 3,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 34,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9530),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9533),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 35,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9540),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9542),
                            EnclosureId = 2,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 36,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9551),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9554),
                            EnclosureId = 4,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 37,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9560),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9563),
                            EnclosureId = 1,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 38,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9569),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9572),
                            EnclosureId = 3,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 39,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9579),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9582),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 40,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9590),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9593),
                            EnclosureId = 3,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 41,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9599),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9602),
                            EnclosureId = 1,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 42,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9608),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9611),
                            EnclosureId = 1,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 43,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9617),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9620),
                            EnclosureId = 1,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 44,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9628),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9631),
                            EnclosureId = 3,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 45,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9638),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9640),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 46,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9647),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9650),
                            EnclosureId = 1,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 47,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9656),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9659),
                            EnclosureId = 2,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 48,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9668),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9670),
                            EnclosureId = 4,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 49,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9677),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9679),
                            EnclosureId = 4,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 50,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9686),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9689),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 51,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9695),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9698),
                            EnclosureId = 1,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 52,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9706),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9709),
                            EnclosureId = 2,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 53,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9715),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9718),
                            EnclosureId = 4,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 54,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9725),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9728),
                            EnclosureId = 2,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 55,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9734),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9737),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 56,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9803),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9806),
                            EnclosureId = 4,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 57,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9812),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9815),
                            EnclosureId = 3,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 58,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9822),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9824),
                            EnclosureId = 3,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 59,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9831),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9833),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 60,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9842),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9845),
                            EnclosureId = 4,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 61,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9851),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9854),
                            EnclosureId = 4,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 62,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9860),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9863),
                            EnclosureId = 4,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 63,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9869),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9872),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 64,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9880),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9883),
                            EnclosureId = 4,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 65,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9889),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9892),
                            EnclosureId = 4,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 66,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9898),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9901),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 67,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9907),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9910),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 68,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9918),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9921),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 69,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9927),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9930),
                            EnclosureId = 4,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 70,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9936),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9939),
                            EnclosureId = 4,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 71,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9945),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9948),
                            EnclosureId = 2,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 72,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9956),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9959),
                            EnclosureId = 2,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 73,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9965),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9968),
                            EnclosureId = 2,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 74,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9974),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9977),
                            EnclosureId = 4,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 75,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9983),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9986),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 76,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9994),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 802, DateTimeKind.Utc).AddTicks(9997),
                            EnclosureId = 3,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 77,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(4),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(6),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 78,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(13),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(16),
                            EnclosureId = 1,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 79,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(22),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(25),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 80,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(33),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(36),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 81,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(42),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(45),
                            EnclosureId = 4,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 82,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(52),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(55),
                            EnclosureId = 1,
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 83,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(61),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(64),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 84,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(72),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(75),
                            EnclosureId = 2,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 85,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(81),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(84),
                            EnclosureId = 3,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 86,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(91),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(93),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 87,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(100),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(103),
                            EnclosureId = 4,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 88,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(111),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(114),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 89,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(121),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(124),
                            EnclosureId = 2,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 90,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(130),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(133),
                            EnclosureId = 2,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 91,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(140),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(142),
                            EnclosureId = 2,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 92,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(151),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(153),
                            EnclosureId = 2,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 93,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(160),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(163),
                            EnclosureId = 1,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 94,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(169),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(172),
                            EnclosureId = 3,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 95,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(179),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(182),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 96,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(190),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(193),
                            EnclosureId = 1,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 97,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(199),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(202),
                            EnclosureId = 4,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 98,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(208),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(211),
                            EnclosureId = 3,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 99,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(217),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(220),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 100,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(269),
                            DateOfBirth = new DateTime(2024, 3, 6, 21, 40, 49, 803, DateTimeKind.Utc).AddTicks(272),
                            EnclosureId = 2,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 1
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 6,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = 2,
                            Classification = 0,
                            Name = "elephant"
                        },
                        new
                        {
                            Id = 3,
                            Classification = 0,
                            Name = "zebra"
                        },
                        new
                        {
                            Id = 4,
                            Classification = 1,
                            Name = "snake"
                        },
                        new
                        {
                            Id = 5,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = 6,
                            Classification = 0,
                            Name = "hippo"
                        },
                        new
                        {
                            Id = 7,
                            Classification = 2,
                            Name = "parrot"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", null)
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
