// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240307133706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7001),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7063),
                            EnclosureId = -5,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -2,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7086),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7089),
                            EnclosureId = -5,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -3,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7096),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7099),
                            EnclosureId = -1,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -4,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7106),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7109),
                            EnclosureId = -5,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -5,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7115),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7118),
                            EnclosureId = -3,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -6,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7127),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7130),
                            EnclosureId = -3,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -7,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7136),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7139),
                            EnclosureId = -2,
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -8,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7146),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7148),
                            EnclosureId = -3,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -9,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7155),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7158),
                            EnclosureId = -4,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -10,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7166),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7169),
                            EnclosureId = -5,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -11,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7175),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7178),
                            EnclosureId = -3,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -12,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7185),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7188),
                            EnclosureId = -3,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -13,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7194),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7197),
                            EnclosureId = -3,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -14,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7205),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7208),
                            EnclosureId = -4,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -15,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7214),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7217),
                            EnclosureId = -1,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -16,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7224),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7227),
                            EnclosureId = -2,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -17,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7233),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7236),
                            EnclosureId = -4,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -18,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7244),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7247),
                            EnclosureId = -1,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -19,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7253),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7256),
                            EnclosureId = -5,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -20,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7262),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7265),
                            EnclosureId = -1,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -21,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7272),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7275),
                            EnclosureId = -1,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -22,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7283),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7286),
                            EnclosureId = -3,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -23,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7292),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7295),
                            EnclosureId = -4,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -24,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7301),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7304),
                            EnclosureId = -3,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -25,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7311),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7314),
                            EnclosureId = -1,
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7372),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7376),
                            EnclosureId = -2,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -27,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7383),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7385),
                            EnclosureId = -5,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -28,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7392),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7395),
                            EnclosureId = -4,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -29,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7401),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7404),
                            EnclosureId = -3,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -30,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7412),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7415),
                            EnclosureId = -3,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7421),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7424),
                            EnclosureId = -1,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7431),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7434),
                            EnclosureId = -5,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -33,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7440),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7443),
                            EnclosureId = -4,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7451),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7454),
                            EnclosureId = -4,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -35,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7460),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7463),
                            EnclosureId = -2,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -36,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7470),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7472),
                            EnclosureId = -3,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -37,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7479),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7482),
                            EnclosureId = -1,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -38,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7490),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7493),
                            EnclosureId = -3,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7499),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7502),
                            EnclosureId = -5,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7508),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7511),
                            EnclosureId = -4,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -41,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7518),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7521),
                            EnclosureId = -2,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -42,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7529),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7532),
                            EnclosureId = -3,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7538),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7541),
                            EnclosureId = -5,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -44,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7547),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7550),
                            EnclosureId = -1,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -45,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7556),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7559),
                            EnclosureId = -4,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -46,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7568),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7571),
                            EnclosureId = -2,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -47,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7577),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7580),
                            EnclosureId = -1,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7586),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7589),
                            EnclosureId = -1,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -49,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7595),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7598),
                            EnclosureId = -5,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -50,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7607),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7610),
                            EnclosureId = -1,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -51,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7616),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7619),
                            EnclosureId = -2,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7625),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7628),
                            EnclosureId = -1,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -53,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7634),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7637),
                            EnclosureId = -1,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -54,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7645),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7648),
                            EnclosureId = -2,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -55,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7655),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7658),
                            EnclosureId = -5,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -56,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7664),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7667),
                            EnclosureId = -3,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -57,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7673),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7676),
                            EnclosureId = -4,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -58,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7684),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7687),
                            EnclosureId = -5,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -59,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7694),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7697),
                            EnclosureId = -4,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7703),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7706),
                            EnclosureId = -5,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -61,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7712),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7715),
                            EnclosureId = -2,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -62,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7724),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7726),
                            EnclosureId = -2,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -63,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7733),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7736),
                            EnclosureId = -3,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -64,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7742),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7745),
                            EnclosureId = -3,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -65,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7751),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7754),
                            EnclosureId = -3,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -66,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7762),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7765),
                            EnclosureId = -3,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -67,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7771),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7774),
                            EnclosureId = -1,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -68,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7781),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7784),
                            EnclosureId = -3,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -69,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7790),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7793),
                            EnclosureId = -3,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -70,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7826),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7829),
                            EnclosureId = -5,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -71,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7836),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7839),
                            EnclosureId = -3,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -72,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7845),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7848),
                            EnclosureId = -3,
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7855),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7858),
                            EnclosureId = -4,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -74,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7866),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7869),
                            EnclosureId = -3,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -75,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7875),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7878),
                            EnclosureId = -3,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -76,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7885),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7887),
                            EnclosureId = -3,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -77,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7894),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7897),
                            EnclosureId = -1,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -78,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7905),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7908),
                            EnclosureId = -4,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7915),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7918),
                            EnclosureId = -4,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -80,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7924),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7927),
                            EnclosureId = -2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -81,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7933),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7936),
                            EnclosureId = -2,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -82,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7944),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7947),
                            EnclosureId = -2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -83,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7954),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7957),
                            EnclosureId = -4,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -84,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7963),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7966),
                            EnclosureId = -5,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -85,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7973),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7975),
                            EnclosureId = -3,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -86,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7984),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7987),
                            EnclosureId = -2,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -87,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7993),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(7996),
                            EnclosureId = -3,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -88,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8002),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8005),
                            EnclosureId = -3,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -89,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8011),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8014),
                            EnclosureId = -3,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -90,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8023),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8026),
                            EnclosureId = -1,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -91,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8032),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8035),
                            EnclosureId = -1,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -92,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8042),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8044),
                            EnclosureId = -5,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -93,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8051),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8054),
                            EnclosureId = -2,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -94,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8062),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8065),
                            EnclosureId = -1,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -95,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8071),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8074),
                            EnclosureId = -4,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -96,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8081),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8084),
                            EnclosureId = -1,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -97,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8090),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8093),
                            EnclosureId = -5,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -98,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8101),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8104),
                            EnclosureId = -5,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -99,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8110),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8113),
                            EnclosureId = -2,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -100,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8120),
                            DateOfBirth = new DateTime(2024, 3, 7, 13, 37, 5, 822, DateTimeKind.Utc).AddTicks(8123),
                            EnclosureId = -4,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = -4
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 6,
                            Type = 3
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 50,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 40,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 0,
                            Name = "elephant"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 0,
                            Name = "zebra"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 1,
                            Name = "snake"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 0,
                            Name = "hippo"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 2,
                            Name = "parrot"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
